apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  role: karpenter-node-laravel
  amiSelectorTerms:
    - id: ami-0c834fa666e5127b5 # AMD AMI
    - id: ami-007e602441b730d63 # ARM AMI
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: laravel-k8s
  subnetSelectorTerms:
      - tags:
          karpenter.sh/discovery: laravel-k8s
