services:
  web:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile-nginx
      args:
        CGI_PASS_HOST: php-fpm
    ports:
      - "8080:80"
    links:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile-php-fpm
