services:
  web:
    image: nginx
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    links:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
