apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: laravel-example
spec:
  replicas: {{ .Values.deployment.minReplicas }}
  selector:
    matchLabels:
      app: laravel-example
  template:
    metadata:
      labels:
        app: laravel-example
    spec:
      initContainers:
        - name: laravel-init
          image: {{ .Values.deployment.images.php_fpm | required "A php-fpm image is required" }}
          env:
            - name: APP_NAME
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: APP_NAME
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: APP_ENV
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: APP_KEY
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: DB_CONNECTION
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: DB_DATABASE
          command:
            - /bin/sh
            - -c
            - php artisan migrate && php artisan optimize
      containers:
        - name: laravel-nginx
          image: {{ .Values.deployment.images.nginx | required "An nginx image is required" }}
          env:
            - name: APP_URL
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: APP_URL
            - name: APP_NAME
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: APP_NAME
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: APP_ENV
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: APP_KEY
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: DB_CONNECTION
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: DB_DATABASE
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            periodSeconds: 5
            failureThreshold: 5
            httpGet:
              path: /up
              port: http
          resources:
            requests:
              cpu: 25m
              memory: "25Mi"
            limits:
              cpu: 50m
              memory: "50Mi"
        - name: laravel-php-fpm
          image: {{ .Values.deployment.images.php_fpm | required "A php-fpm image is required" }}
          env:
            - name: APP_URL
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: APP_URL
            - name: APP_NAME
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: APP_NAME
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: APP_ENV
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: APP_KEY
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: DB_CONNECTION
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: laravel-app-env
                  key: DB_DATABASE
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: 50m
              memory: "75Mi"
            limits:
              cpu: 150m
              memory: "150Mi"
