apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: laravel-app-env
  namespace: {{ .Values.namespace }}
spec:
  target:
    name: laravel-app-env
  secretStoreRef:
    name: laravel-app-env
    kind: SecretStore
  data:
    - secretKey: APP_URL
      remoteRef:
        key: /laravel-k8s/dev/APP_URL
    - secretKey: APP_NAME
      remoteRef:
        key: /laravel-k8s/dev/APP_NAME
    - secretKey: APP_ENV
      remoteRef:
        key: /laravel-k8s/dev/APP_ENV
    - secretKey: APP_KEY
      remoteRef:
        key: /laravel-k8s/dev/APP_KEY
    - secretKey: DB_CONNECTION
      remoteRef:
        key: /laravel-k8s/dev/DB_CONNECTION
    - secretKey: DB_HOST
      remoteRef:
        key: /laravel-k8s/dev/DB_HOST
    - secretKey: DB_USERNAME
      remoteRef:
        key: /laravel-k8s/dev/DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /laravel-k8s/dev/DB_PASSWORD
    - secretKey: DB_DATABASE
      remoteRef:
        key: /laravel-k8s/dev/DB_DATABASE
