apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laravel
  namespace: {{ .Values.namespace }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/load-balancer-name: laravel-k8s-external
    alb.ingress.kubernetes.io/group.name: laravel-k8s-external
    alb.ingress.kubernetes.io/healthcheck-path: /up
    external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
    # Assign a specific hostname for external DNS to point at the ALB
    # so that CloudFront can use it as a custom origin
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.alb_domain | required "A valid ALB domain is required" }}
    {{ range .Values.ingress.load_balancer.front_end_security_group_ids }}
    alb.ingress.kubernetes.io/security-groups: {{ . }}
    {{ end }}
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.domain | required "A valid application domain is required" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: laravel-service
                port:
                  number: 80
