apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: laravel-app-env
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  secretObjects:
    - secretName: laravel-app-env
      type: Opaque
      data:
        - objectName: APP_NAME
          key: APP_NAME
        - objectName: APP_ENV
          key: APP_ENV
        - objectName: APP_KEY
          key: APP_KEY
        - objectName: DB_CONNECTION
          key: DB_CONNECTION
        - objectName: DB_HOST
          key: DB_HOST
        - objectName: DB_USERNAME
          key: DB_USERNAME
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
        - objectName: DB_DATABASE
          key: DB_DATABASE
  parameters:
    objects: |
      - objectName: "/laravel-k8s/dev/APP_NAME"
        objectType: "ssmparameter"
        objectAlias: APP_NAME
      - objectName: "/laravel-k8s/dev/APP_ENV"
        objectType: "ssmparameter"
        objectAlias: APP_ENV
      - objectName: "/laravel-k8s/dev/APP_KEY"
        objectType: "ssmparameter"
        objectAlias: APP_KEY
      - objectName: "/laravel-k8s/dev/DB_CONNECTION"
        objectType: "ssmparameter"
        objectAlias: DB_CONNECTION
      - objectName: "/laravel-k8s/dev/DB_USERNAME"
        objectType: "ssmparameter"
        objectAlias: DB_USERNAME
      - objectName: "/laravel-k8s/dev/DB_PASSWORD"
        objectType: "ssmparameter"
        objectAlias: DB_PASSWORD
      - objectName: "/laravel-k8s/dev/DB_HOST"
        objectType: "ssmparameter"
        objectAlias: DB_HOST
      - objectName: "/laravel-k8s/dev/DB_DATABASE"
        objectType: "ssmparameter"
        objectAlias: DB_DATABASE
