apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.secrets_provider_controller_service_account.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ required "A role ARN for the secrets provider service account is required" .Values.secrets_provider_controller_service_account.role_arn  }}
