apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: laravel-app-env
  namespace: {{ .Values.namespace }}
spec:
  provider:
    aws:
      service: ParameterStore
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.secrets_provider_controller_service_account.name }}
      region: us-east-1
