apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: laravel-app-env
  namespace: laravel
spec:
  provider: aws
  secretObjects:
    - secretName: laravel-app-env
      type: Opaque
      data:
        - objectName: APP_NAME
          key: APP_NAME
  parameters:
    objects: |
      - objectName: "/laravel-k8s/dev/APP_NAME"
        objectType: "ssmparameter"
        objectAlias: APP_NAME
