apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: laravel
spec:
  selector:
    app: laravel-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
