apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cloudflare-api
  namespace: kube-system
spec:
  provider: aws
  secretObjects:
    - secretName: cloudflare-api
      type: Opaque
      data:
        - objectName: API_TOKEN
          key: API_TOKEN
  parameters:
    objects: |
      - objectName: "/laravel-k8s/cloudflare/api_token"
        objectType: "ssmparameter"
        objectAlias: API_TOKEN
