apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: cloudflare-api-store
  namespace: kube-system
spec:
  provider:
    aws:
      service: ParameterStore
      auth:
        jwt:
          serviceAccountRef:
            name: external-dns
      region: us-east-1
