apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-external-secrets
  namespace: kube-system
spec:
  target:
    name: cloudflare-api
  secretStoreRef:
    name: cloudflare-api-store
    kind: SecretStore
  data:
    - secretKey: API_TOKEN
      remoteRef:
        key: /laravel-k8s/cloudflare/api_token
