apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::654654165875:role/AmazonEKSLoadBalancerControllerRole
