apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.load_balancer_controller_service_account.name }}
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: {{ required "A role ARN for the AWS load balancer service account is required" .Values.load_balancer_controller_service_account.role_arn  }}
