namespace: laravel
domain: # REQUIRED
alb_domain: # REQUIRED
secrets_provider_controller_service_account:
  name: external-secrets
  role_arn: # REQUIRED
service:
  name: laravel-service
  port: 80
  targetPort: 80
deployment:
  replicas: 3
  images:
    nginx: # REQUIRED
    php_fpm: # REQUIRED
ingress:
  loadBalancer:
    securityGroupIds: []
