name: 🛠️ DEV - Build Images
on:
  push:
    branches:
      - main
    paths:
      - application/**/*
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  buildPhpFpmImage:
    name: Build php-fpm image
    uses: ./.github/workflows/reusable-build-image.yaml
    secrets: inherit
    with:
      ENVIRONMENT: dev
      IMAGE_NAME: fly-laravel-php-fpm
