name: 🛠️ DEV - Build Images
on:
  push:
    branches:
      - main
      - dev
    paths:
      - application/**/*
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  buildPhpFpmImage:
    name: Build php-fpm image
    uses: ./.github/workflows/reusable-build-image.yaml
    secrets: inherit
    with:
      ENVIRONMENT: dev
      DOCKERFILE_PATH: ./application/.docker/Dockerfile.php-fpm
      IMAGE_NAME: fly-laravel-php-fpm
  buildNginxImage:
    name: Build nginx image
    uses: ./.github/workflows/reusable-build-image.yaml
    secrets: inherit
    with:
      ENVIRONMENT: dev
      DOCKERFILE_PATH: ./application/.docker/Dockerfile.nginx
      IMAGE_NAME: fly-laravel-nginx
