name: ⚙️ Reusable Build Image
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      DOCKERFILE_PATH:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
jobs:
  BuildImage:
    environment: ${{inputs.ENVIRONMENT}}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_EXECUTION_ROLE}}
          aws-region: "us-east-1"
      - name: Login to Amazon ECR
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.ECR_URL}}${{inputs.IMAGE_NAME}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build, tag, and push docker image to Amazon ECR
        uses: docker/build-push-action@v4
        with:
          context: ./application
          platforms: linux/arm64, linux/amd64
          file: ${{inputs.DOCKERFILE_PATH}}
          push: true
          tags: |
            ${{secrets.ECR_URL}}${{inputs.IMAGE_NAME}}:${{ github.sha }}
            ${{secrets.ECR_URL}}${{inputs.IMAGE_NAME}}:latest
